---
apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
metadata:
  # Fleet Metadata
  # https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#objectmeta-v1-meta
  name: rust-server
spec:
  # the number of GameServers to keep Ready or Allocated in this Fleet
  replicas: 1
  # a GameServer template - see:
  # https://github.com/GoogleCloudPlatform/agones/blob/master/docs/gameserver_spec.md for all the options
  strategy:
    # The replacement strategy for when the GameServer template is changed. Default option is "RollingUpdate",
    # "RollingUpdate" will increment by maxSurge value on each iteration, while decrementing by maxUnavailable on each
    # iteration, until all GameServers have been switched from one version to another.
    # "Recreate" terminates all non-allocated GameServers, and starts up a new set with the new details to replace them.
    type: RollingUpdate
    # Only relevant when `type: RollingUpdate`
    rollingUpdate:
      # the amount to increment the new GameServers by. Defaults to 25%
      maxSurge: 25%
      # the amount to decrements GameServers by. Defaults to 25%
      maxUnavailable: 25%
  template:
    # GameServer metadata
    metadata:
      labels:
        game: rust
    # GameServer specification
    spec:
      portPolicy: "dynamic"
      containerPort: 28015
      health:
        # Disable health checking. defaults to false, but can be set to true
        disabled: true
        # Number of seconds after the container has started before health check is initiated. Defaults to 5 seconds
        initialDelaySeconds: 5
        # If the `Health()` function doesn't get called at least once every period (seconds), then
        # the game server is not healthy. Defaults to 5
        periodSeconds: 5
        # Minimum consecutive failures for the health probe to be considered failed after having succeeded.
        # Defaults to 3. Minimum value is 1
        failureThreshold: 3

      # The GameServer's Pod template
      template:
        spec:
          containers:
          - name: rust-server
            image: didstopia/rust-server

